name: Pentaho Merge Compliance
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
      - "+([0-9])*(.+([0-9]))"
    paths-ignore:
      - .github/**
jobs:
  run-merge-compliance:
    name: Run Merge Compliance Checks
    uses: pentaho/actions-common/.github/workflows/merge_compliance.yml@compliance
    with:
      scpId: ${{ vars.THREATRIX_PDIA_SCP_ID }}
    secrets: inherit

